version: "3.9"

services:
  analyzer:
    build: .
    container_name: cyber_analyzer
    volumes:
      - ./sample_logs/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "src/main.py"]
